# exporter.py

"""Module responsible for exporting the generated report to different file formats."""

import os
import pandas as pd
from fpdf import FPDF
from typing import Dict, Any


def _prepare_data_for_export(report_data: Dict[str, Any]) -> Dict[str, pd.DataFrame]:
    """
    Prepares the report data into a standardized dictionary of DataFrames for export.

    Args:
        report_data (Dict[str, Any]): The raw report data generated by `report_builder`.

    Returns:
        Dict[str, pd.DataFrame]: A dictionary where keys are report section names
                                 and values are pandas DataFrames ready for export.
    """
    export_data: Dict[str, pd.DataFrame] = {}

    if "total" in report_data:
        export_data["total"] = pd.DataFrame({'Grand Total': [report_data['total']]})

    if "categories" in report_data and isinstance(report_data["categories"], pd.Series):
        export_data["categories"] = report_data["categories"].reset_index().rename(
            columns={'index': 'Category', 0: 'Amount'}
        )

    if "months" in report_data and isinstance(report_data["months"], pd.Series):
        export_data["months"] = report_data["months"].reset_index().rename(
            columns={'index': 'Month', 0: 'Amount'}
        )

    if "filtered_category" in report_data:
        df = report_data["filtered_category"].copy()
        if 'month' in df.columns:
            df = df.drop(columns=['month'])
        export_data["filtered_category"] = df

    if "filtered_month" in report_data:
        df = report_data["filtered_month"].copy()
        if 'month' in df.columns:
            df = df.drop(columns=['month'])
        export_data["filtered_month"] = df

    return export_data


def _export_pdf(report_string: str, output_dir: str) -> None:
    """
    Exports the report as a PDF file.

    Args:
        report_string (str): The formatted report content as a single string.
        output_dir (str): The directory where the PDF file will be saved.
    """
    pdf = FPDF()
    pdf.set_margins(left=20, top=20, right=20)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    pdf.set_font("Courier", size=9)
    pdf.write(5, report_string)
    pdf.output(os.path.join(output_dir, "report.pdf"))
    print(f"✅ Report successfully exported to '{output_dir}' as PDF!")


def _export_txt(report_string: str, output_dir: str) -> None:
    """
    Exports the report as a plain text file.

    Args:
        report_string (str): The formatted report content as a single string.
        output_dir (str): The directory where the TXT file will be saved.
    """
    with open(os.path.join(output_dir, "report.txt"), "w", encoding="utf-8") as file:
        file.write(report_string)
    print(f"✅ Report successfully exported to '{output_dir}' as TXT!")


def _export_csv(data: Dict[str, pd.DataFrame], output_dir: str) -> None:
    """
    Exports structured report data to multiple CSV files.
    Each DataFrame in the input dictionary will be saved as a separate CSV file.

    Args:
        data (Dict[str, pd.DataFrame]): A dictionary of DataFrames to be exported.
        output_dir (str): The directory where the CSV files will be saved.
    """
    for key, df in data.items():
        if isinstance(df, pd.DataFrame):
            filename = f"report_{key}.csv"
            df.to_csv(os.path.join(output_dir, filename), index=False)
    print(f"✅ Report successfully exported to '{output_dir}' as CSV!")


def _export_excel(data: Dict[str, pd.DataFrame], output_dir: str) -> None:
    """
    Exports structured report data to a single Excel workbook with multiple sheets.
    Each DataFrame in the input dictionary will be saved as a separate sheet.

    Args:
        data (Dict[str, pd.DataFrame]): A dictionary of DataFrames to be exported.
        output_dir (str): The directory where the Excel file will be saved.
    """
    excel_path = os.path.join(output_dir, "report.xlsx")
    with pd.ExcelWriter(excel_path, engine='xlsxwriter') as writer:
        for key, df in data.items():
            if isinstance(df, pd.DataFrame):
                sheet_name = key.replace("_", " ").title()[:31]  # Excel limits sheet name length
                df.to_excel(writer, sheet_name=sheet_name, index=False)
    print(f"✅ Report successfully exported to '{output_dir}' as Excel!")


def _export_html(report_data: Dict[str, Any], output_dir: str) -> None:
    """
    Exports the report as a well-formatted and styled HTML file.

    Args:
        report_data (Dict[str, Any]): The raw report data generated by `report_builder`.
        output_dir (str): The directory where the HTML file will be saved.
    """
    css = """
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; background-color: #f0f2f5; color: #333; }
        .report-card { background: #fff; padding: 40px; border-radius: 12px; box-shadow: 0 10px 25px rgba(0,0,0,0.1); max-width: 1000px; margin: auto; }
        header { text-align: center; margin-bottom: 40px; border-bottom: 3px solid #007bff; padding-bottom: 20px; }
        h1 { color: #1a1a1a; margin: 0; text-transform: uppercase; letter-spacing: 2px; }
        h2 { color: #007bff; border-left: 4px solid #007bff; padding-left: 15px; margin-top: 40px; font-size: 1.4rem; }
        .grand-total { background: linear-gradient(135deg, #007bff 0%, #0056b3 100%); color: white; padding: 25px; border-radius: 8px; text-align: center; margin: 30px 0; }
        .grand-total span { display: block; font-size: 0.9rem; opacity: 0.9; text-transform: uppercase; }
        .grand-total strong { font-size: 2.5rem; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th { background-color: #f8f9fa; color: #495057; font-weight: 600; text-transform: uppercase; font-size: 0.85rem; padding: 12px; border-bottom: 2px solid #dee2e6; text-align: left; }
        td { padding: 12px; border-bottom: 1px solid #eee; color: #333; }
        tr:nth-child(even) { background-color: #fafafa; }
        tr:hover { background-color: #f1f8ff; }
    </style>
    """
    
    html_parts = [f"<html><head><meta charset='utf-8'>{css}</head><body><div class='report-card'>"]
    html_parts.append("<header><h1>Business Report</h1></header>")

    if "total" in report_data:
        html_parts.append(f"<div class='grand-total'><span>Grand Total</span><strong>${report_data['total']:,.2f}</strong></div>")

    if "categories" in report_data and isinstance(report_data["categories"], pd.Series):
        html_parts.append("<h2>Total by Category</h2>")
        df_cat = report_data["categories"].reset_index()
        df_cat.columns = ['Category', 'Amount']
        html_parts.append(df_cat.to_html(index=False, border=0, justify='left', float_format=lambda x: f'${x:,.2f}'))

    if "months" in report_data and isinstance(report_data["months"], pd.Series):
        html_parts.append("<h2>Total by Month</h2>")
        df_month = report_data["months"].reset_index()
        df_month.columns = ['Month', 'Amount']
        html_parts.append(df_month.to_html(index=False, border=0, justify='left', float_format=lambda x: f'${x:,.2f}'))

    if "filtered_category" in report_data:
        cat_name = report_data.get('selected_category', 'N/A')
        html_parts.append(f"<h2>Filtered Details: {cat_name}</h2>")
        df = report_data["filtered_category"].copy()
        if 'date' in df.columns:
            df['date'] = df['date'].dt.strftime('%Y-%m-%d')
        if 'month' in df.columns:
            df = df.drop(columns=['month'])
        html_parts.append(df.to_html(index=False, border=0, justify='left', float_format=lambda x: f'${x:,.2f}'))

    if "filtered_month" in report_data:
        month_name = report_data.get('selected_month', 'N/A')
        html_parts.append(f"<h2>Filtered Details: {month_name}</h2>")
        df = report_data["filtered_month"].copy()
        if 'date' in df.columns:
            df['date'] = df['date'].dt.strftime('%Y-%m-%d')
        if 'month' in df.columns:
            df = df.drop(columns=['month'])
        html_parts.append(df.to_html(index=False, border=0, justify='left', float_format=lambda x: f'${x:,.2f}'))

    html_parts.append("</div></body></html>")
    
    with open(os.path.join(output_dir, "report.html"), "w", encoding='utf-8') as file:
        file.write("\n".join(html_parts))


def export_report(report_data: dict, report_string: str, export_format: str):
    """Export the report to the specified file format."""
    output_dir = "Reports"
    os.makedirs(output_dir, exist_ok=True)

    data = _prepare_data_for_export(report_data)

    if export_format == "PDF":
        _export_pdf(report_string, output_dir)
    elif export_format == "TXT":
        _export_txt(report_string, output_dir)
    elif export_format == "CSV":
        _export_csv(data, output_dir)
    elif export_format == "Excel":
        _export_excel(data, output_dir)
    elif export_format == "HTML":
        _export_html(report_data, output_dir)
    else:
        print(f"Unsupported format: {export_format}")

    print(f"✅ Report successfully exported to '{output_dir}' as {export_format}!")